### ISSUE TITLE
Should it work?

### ISSUE THREAD

**Issue by psturc** [feedhenry/negotiator#8]
Hey @maleck13 and @philbrookes,

this looks awesome!

I'm not sure about the current functionality of this guy - readme says "currently it just sets up a service, a route and an imagestream", but I see some commits about adding BuildConfig and DeploymentConfig, so I'm not sure if it should currently work...?

By following the instructions, the tool created imagestream, services, route, secrets and dc for redis.
However it failed on creating BuildConfig for cloud-testguid:

`failed to create BuildConfig: BuildConfig "cloud-testguid" is invalid: spec.source.git.uri: Required value`

When I run unit tests, I get the following:
```
> $ make test-unit                                                                               ⬡ 0.10.42 [±master ✓]
go test -v -cpu=2 `go list ./... | grep -v /vendor/`
?   	github.com/feedhenry/negotiator	[no test files]
?   	github.com/feedhenry/negotiator/config	[no test files]
?   	github.com/feedhenry/negotiator/controller	[no test files]
# github.com/feedhenry/negotiator/domain/openshift_test
domain/openshift/service_test.go:135: cannot use mockClient (type MockPassClient) as type openshift.PaaSClient in argument to openshift.NewService:
	MockPassClient does not implement openshift.PaaSClient (missing CreateBuildConfigInNamespace method)
domain/openshift/service_test.go:136: too many arguments in call to underTest.CreateService
domain/openshift/service_test.go:136: assignment count mismatch: 2 = 1
FAIL	github.com/feedhenry/negotiator/domain/openshift [build failed]
testing: warning: no tests to run
PASS
ok  	github.com/feedhenry/negotiator/domain/rhmap	0.009s
?   	github.com/feedhenry/negotiator/endpoint	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/feedhenry/negotiator/pkg/openshift	0.026s
make: *** [test-unit] Error 2
```

Thanks!

**Comment by philbrookes** [comment]
Ah, this is my fault. I updated the code without updating the readme! I will submit a  PR to correct this and the failing tests as soon as I can.
